### ISSUE TITLE
getPlayerExact

### ISSUE THREAD

**Issue by AhmHkn0** [craftaro/FabledSkyBlock#34]
Instead of "**Bukkit.getPlayer(uuid);**" method, "**Bukkit.getPlayerExact(uuid);**" should be used. For example, let there be a player named "**juggak111**" on the server. Using the command "**/island coop juggak**", the server will return the player named "**juggak111**".

Actually this problem already exists in FabledSkyBlock. As far as I have tried, it only happens in the Coop event. It might be happening in other places too.

**Comment by SpraxDev** [comment]
Thanks for your report – The issue will be fixed with the next update
